### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by obazoud** [tacitknowledge/flip#4]
I try to build Flip project from an empty repository with an empty settings.xml.
Any ideas ?

Maven configuration, running on Ubuntu 12.04 64 bits

```
 % mvn -v
Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Maven home: /usr/local/maven/default
Java version: 1.7.0_04, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.7.0_04/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-27-generic", arch: "amd64", family: "unix"
```

Stack trace:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] flip-parent ....................................... SUCCESS [2:39.071s]
[INFO] Flip Core ......................................... FAILURE [54.053s]
[INFO] Flip Servlet ...................................... SKIPPED
[INFO] Flip AspectJ ...................................... SKIPPED
[INFO] Flip Spring ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:17.251s
[INFO] Finished at: Fri Aug 03 08:56:24 CEST 2012
[INFO] Final Memory: 16M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.sun.tools.jxc.maven2:maven-jaxb-schemagen-plugin:1.2:generate (default) on project core: Execution default of goal com.sun.tools.jxc.maven2:maven-jaxb-schemagen-plugin:1.2:generate failed: A required class was missing while executing com.sun.tools.jxc.maven2:maven-jaxb-schemagen-plugin:1.2:generate: com/sun/mirror/apt/AnnotationProcessorFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sun.tools.jxc.maven2:maven-jaxb-schemagen-plugin:1.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/olivier/.m2/repository/com/sun/tools/jxc/maven2/maven-jaxb-schemagen-plugin/1.2/maven-jaxb-schemagen-plugin-1.2.jar
[ERROR] urls[1] = file:/home/olivier/.m2/repository/javax/xml/bind/jaxb-api/2.2/jaxb-api-2.2.jar
[ERROR] urls[2] = file:/home/olivier/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
[ERROR] urls[3] = file:/home/olivier/.m2/repository/com/sun/xml/bind/jaxb-xjc/2.2/jaxb-xjc-2.2.jar
[ERROR] urls[4] = file:/home/olivier/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2/jaxb-impl-2.2.jar
[ERROR] urls[5] = file:/home/olivier/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
[ERROR] urls[6] = file:/home/olivier/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[7] = file:/home/olivier/.m2/repository/ant/ant/1.6.5/ant-1.6.5.jar
[ERROR] urls[8] = file:/home/olivier/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
[ERROR] urls[9] = file:/home/olivier/.m2/repository/javax/xml/bind/jsr173_api/1.0/jsr173_api-1.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.tacitknowledge.flip:core:1.0.1-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.sun.mirror.apt.AnnotationProcessorFactory
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

```

**Comment by Nanduyana** [comment]
can you help in solving this issue pls

we have jdk 1.8 in path and the plugin supports jdk6 

jdk 1.8 doesnt have tools.jar support 

Caused by: java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory
	at com.sun.tools.jxc.maven2.SchemaGenMojo.execute(SchemaGenMojo.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 31 more
Caused by: java.lang.ClassNotFoundException: com.sun.mirror.apt.AnnotationProcessorFactory
